use crate::error::{IpCalcError, Result};
use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct ServerConfig {
    /// Maximum CIDRs in a single batch request
    pub max_batch_size: usize,
    /// Maximum CIDRs generated by from-range
    pub max_generated_cidrs: usize,
    /// Maximum input CIDRs for summarize
    pub max_summarize_inputs: usize,
    /// Maximum request body size in bytes
    pub max_body_size: usize,
    /// Rate limit: sustained requests per second
    pub rate_limit_per_second: u64,
    /// Rate limit: burst size
    pub rate_limit_burst: u32,
    /// Request timeout in seconds
    pub timeout_seconds: u64,
    /// Enable Swagger UI
    pub enable_swagger: bool,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            max_batch_size: 10_000,
            max_generated_cidrs: 1_000_000,
            max_summarize_inputs: 10_000,
            max_body_size: 1_048_576, // 1 MB
            rate_limit_per_second: 20,
            rate_limit_burst: 50,
            timeout_seconds: 30,
            enable_swagger: false,
        }
    }
}

#[derive(Debug, Default)]
pub struct CliOverrides {
    pub enable_swagger: bool,
    pub max_batch_size: Option<usize>,
    pub max_range_cidrs: Option<usize>,
    pub max_summarize_inputs: Option<usize>,
    pub max_body_size: Option<usize>,
    pub rate_limit_per_second: Option<u64>,
    pub rate_limit_burst: Option<u32>,
    pub timeout: Option<u64>,
}

impl ServerConfig {
    pub fn load(path: &str) -> Result<Self> {
        // nosemgrep: path-traversal — CLI-only startup config, not reachable from HTTP input
        let contents = std::fs::read_to_string(path)?;
        let config: ServerConfig =
            toml::from_str(&contents).map_err(|e| IpCalcError::ConfigParse(e.to_string()))?;
        Ok(config)
    }

    pub fn merge_cli_overrides(&mut self, overrides: &CliOverrides) {
        if overrides.enable_swagger {
            self.enable_swagger = true;
        }
        if let Some(v) = overrides.max_batch_size {
            self.max_batch_size = v;
        }
        if let Some(v) = overrides.max_range_cidrs {
            self.max_generated_cidrs = v;
        }
        if let Some(v) = overrides.max_summarize_inputs {
            self.max_summarize_inputs = v;
        }
        if let Some(v) = overrides.max_body_size {
            self.max_body_size = v;
        }
        if let Some(v) = overrides.rate_limit_per_second {
            self.rate_limit_per_second = v;
        }
        if let Some(v) = overrides.rate_limit_burst {
            self.rate_limit_burst = v;
        }
        if let Some(v) = overrides.timeout {
            self.timeout_seconds = v;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = ServerConfig::default();
        assert_eq!(config.max_batch_size, 10_000);
        assert_eq!(config.max_generated_cidrs, 1_000_000);
        assert_eq!(config.max_summarize_inputs, 10_000);
        assert_eq!(config.max_body_size, 1_048_576);
        assert_eq!(config.rate_limit_per_second, 20);
        assert_eq!(config.rate_limit_burst, 50);
        assert_eq!(config.timeout_seconds, 30);
        assert!(!config.enable_swagger);
    }

    #[test]
    fn test_merge_cli_overrides() {
        let mut config = ServerConfig::default();
        config.merge_cli_overrides(&CliOverrides {
            enable_swagger: true,
            max_batch_size: Some(500),
            timeout: Some(60),
            ..Default::default()
        });
        assert!(config.enable_swagger);
        assert_eq!(config.max_batch_size, 500);
        assert_eq!(config.max_generated_cidrs, 1_000_000); // unchanged
        assert_eq!(config.timeout_seconds, 60);
    }

    #[test]
    fn test_toml_deserialization() {
        let toml_str = r#"
            max_batch_size = 500
            enable_swagger = true
        "#;
        let config: ServerConfig = toml::from_str(toml_str).unwrap();
        assert_eq!(config.max_batch_size, 500);
        assert!(config.enable_swagger);
        // defaults for unspecified fields
        assert_eq!(config.max_generated_cidrs, 1_000_000);
    }
}
